site_name: GTM Knowledge Base
site_description: "Drill-down GTM knowledge base: Pain Points and Technical vendor mapping"

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs           # shows top tabs for top-level items only
    - navigation.top            # back-to-top button
    - navigation.sections       # tidy section headings in left nav
    - navigation.indexes        # section headers are clickable (landing pages)
    - toc.integrate             # page ToC integrated into left sidebar
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Pain Points: pain-points/index.md
  - Technical: technical/index.md
