site_name: GTM Knowledge Base
site_description: "Drill-down GTM knowledge base: Pain Points and Technical vendor mapping"

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Pain Points: pain-points/index.md
  - Pain Points Catalog:
      - Cost Optimization: pain-points/cost-optimization/index.md
      - Performance & Scale: pain-points/performance-scale/index.md
      - Resiliency & Ransomware: pain-points/resiliency-ransomware/index.md
      - Complexity & Ops Automation: pain-points/complexity-ops/index.md
      - Cloud / Hybrid / Edge: pain-points/cloud-hybrid-edge/index.md
      - Security & Compliance: pain-points/security-compliance/index.md
      - Vendor Lock-In & Lifecycle: pain-points/vendor-lockin-lifecycle/index.md
  - Technical: technical/index.md
  - Domains:
      - Compute: technical/compute/index.md
      - Block Storage: technical/block-storage/index.md
      - File Storage: technical/file-storage/index.md
      - Object Storage: technical/object-storage/index.md
      - Backup: technical/backup/index.md
      - Networking: technical/networking/index.md
      - Firewall: technical/firewall/index.md
  - Vendors (Compute):
      - Dell (Rank 1): technical/compute/dell/index.md
      - Cisco (Rank 2): technical/compute/cisco/index.md
      - HPE (Rank 3): technical/compute/hpe/index.md
  - Vendors (Block Storage):
      - Dell (Rank 1): technical/block-storage/dell/index.md
      - Pure (Rank 2): technical/block-storage/pure/index.md
  - Vendors (File Storage):
      - Dell (Rank 1): technical/file-storage/dell/index.md
      - NetApp (Rank 2): technical/file-storage/netapp/index.md
  - Vendors (Object Storage):
      - Dell (Rank 1): technical/object-storage/dell/index.md
      - NetApp (Rank 2): technical/object-storage/netapp/index.md
      - Pure (Rank 3): technical/object-storage/pure/index.md
  - Vendors (Backup):
      - Rubrik (Rank 1): technical/backup/rubrik/index.md
      - Dell (Rank 2): technical/backup/dell/index.md
      - Commvault (Rank 3): technical/backup/commvault/index.md
      - Cohesity (Rank 4): technical/backup/cohesity/index.md
      - Veeam (Rank 5): technical/backup/veeam/index.md
  - Vendors (Networking):
      - Dell (Rank 1): technical/networking/dell/index.md
      - Fortinet (Rank 2): technical/networking/fortinet/index.md
      - Cisco (Rank 3): technical/networking/cisco/index.md
      - HPE-Aruba-Juniper (Rank 4): technical/networking/hpe-aruba-juniper/index.md
      - Palo Alto (Rank 5): technical/networking/palo-alto/index.md
  - Vendors (Firewall):
      - Cisco (Rank 1): technical/firewall/cisco/index.md
      - FortiGate (Rank 2): technical/firewall/fortigate/index.md
