site_name: GTM Knowledge Base
site_description: "Drill-down GTM knowledge base: Pain Points and Technical vendor mapping"

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Pain Points:
      - Cost Optimization: pain-points/cost-optimization/index.md
      - Performance & Scale: pain-points/performance-scale/index.md
      - Resiliency & Ransomware: pain-points/resiliency-ransomware/index.md
      - Complexity & Ops Automation: pain-points/complexity-ops/index.md
      - Cloud / Hybrid / Edge: pain-points/cloud-hybrid-edge/index.md
      - Security & Compliance: pain-points/security-compliance/index.md
      - Vendor Lock-In & Lifecycle: pain-points/vendor-lockin-lifecycle/index.md
  - Technical:
      - Compute:
          - Overview: technical/compute/index.md
          - Dell (Rank 1): technical/compute/dell/index.md
          - Cisco (Rank 2): technical/compute/cisco/index.md
          - HPE (Rank 3): technical/compute/hpe/index.md
      - Block Storage:
          - Overview: technical/block-storage/index.md
          - Dell (Rank 1): technical/block-storage/dell/index.md
          - Pure (Rank 2): technical/block-storage/pure/index.md
      - File Storage:
          - Overview: technical/file-storage/index.md
          - Dell (Rank 1): technical/file-storage/dell/index.md
          - NetApp (Rank 2): technical/file-storage/netapp/index.md
      - Object Storage:
          - Overview: technical/object-storage/index.md
          - Dell (Rank 1): technical/object-storage/dell/index.md
          - NetApp (Rank 2): technical/object-storage/netapp/index.md
          - Pure (Rank 3): technical/object-storage/pure/index.md
      - Backup:
          - Overview: technical/backup/index.md
          - Rubrik (Rank 1): technical/backup/rubrik/index.md
          - Dell (Rank 2): technical/backup/dell/index.md
          - Commvault (Rank 3): technical/backup/commvault/index.md
          - Cohesity (Rank 4): technical/backup/cohesity/index.md
          - Veeam (Rank 5): technical/backup/veeam/index.md
      - Networking:
          - Overview: technical/networking/index.md
          - Dell (Rank 1): technical/networking/dell/index.md
          - Fortinet (Rank 2): technical/networking/fortinet/index.md
          - Cisco (Rank 3): technical/networking/cisco/index.md
          - HPE-Aruba-Juniper (Rank 4): technical/networking/hpe-aruba-juniper/index.md
          - Palo Alto (Rank 5): technical/networking/palo-alto/index.md
      - Firewall:
          - Overview: technical/firewall/index.md
          - Cisco (Rank 1): technical/firewall/cisco/index.md
          - FortiGate (Rank 2): technical/firewall/fortigate/index.md
